[workspace]
members = ["cmd/*", "pkg/*", "internal/*"]

[workspace.package]
version = "0.0.0"
authors = ["Bruno De Simone"]
description = "A short description of my package"
documentation = "https://example.com/bar"